### ISSUE TITLE
Errors with `interface` and `type` in components

### ISSUE THREAD

**Issue by MuhammadM1998** [antfu/nuxt-module-eslint-config#3] opened 2024-01-20 18:40 UTC
### Describe the bug

Hello 👋. In the README it says 
> The module installs the JS, TS and Vue plugins with their recommended rules.

So I thought If I didn't have any custom config before then all I need to do is set up the module. It does work except for this wired error when an `interface` or `type`. Have I missed something?

**Steps to reproduce**
- Open the reproduction link
- Run `npx eslint .` in the terminal
- You'll get 'error  Parsing error: The keyword 'interface' is reserved'
- Comment the `interface` part and run `npx eslint .`
- You'll get 'Parsing error: Unexpected token ThisErrorsToo'

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qf3elk?file=app.vue

### System Info

```Shell
System:
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 18.18.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.3 - /usr/local/bin/npm
  pnpm: 8.14.0 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-03-11 14:42
I guess you would need to have typescript installed?

Your production link is broken.

**Comment by antfu** [comment] 2024-03-11 14:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2024-03-11 14:42 UTC
